server:
  port: 8080

spring:
  application:
    name: springboot_learn
    datasource:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: hzero
      password: Q4E%kizUy2#m
      driver-class-name: com.mysql.cj.jdbc.Driver
